Fix frontend styling
VandorpeDavid/WEBA pull request #5
Opened 2021-06-23 20:30 UTC by VRonsyn

- Fix frontend styling for:
    - Order page
    - Order confirm page
    - Bar page
    - Information page
- Add routing for info page

2021-06-23 22:14 UTC, VandorpeDavid requested changes

2021-06-23 22:14 UTC, VandorpeDavid commented on src/main/java/be/winagent/weba2/controllers/HomeController.java
> +    public String info(@RequestParam(required = false) String lang, @ModelAttribute(name = "currentUser") User currentUser) {
What is this `lang` parameter for? Won't this conflict with the parameter for the switching locale?

If you need the locale for the current user, just add `Locale locale` as a method param.
https://stackoverflow.com/a/33050046

2021-06-24 11:40 UTC, robinvandevyver submitted a review, later dismissed

2021-06-24 15:34 UTC, robinvandevyver approved these changes

2021-06-24 15:41 UTC, VandorpeDavid approved these changes

2021-06-24 15:44 UTC, merged